<a href="https://colab.research.google.com/github/viktoruebelhart/studies/blob/main/00_Pytorch_Bourke.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## 00. Pytorch Fundamentals

In [2]:
!nvidia-smi

Sun Jan 12 22:19:19 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensor

### Creating tensor

Pytorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html



In [4]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/main/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9272, 0.3337, 0.5168, 0.4070],
        [0.5429, 0.7727, 0.3474, 0.4886],
        [0.9166, 0.9472, 0.2001, 0.4937]])

In [18]:
#Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(3, 224, 224)  # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [19]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & Deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensor not on the right device

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= torch.float32, # what datatype is the tensor (e.g. float32 or float16)
                               device= None, # what device is your tensor on
                               requires_grad= False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors

1. Tensors not right datatype   - `tensor.dtype`
2. Tensors not right shape      - `tensor.shape`
3. Tensor not on the right device - `tensor.device`

In [31]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2222, 0.0057, 0.3002, 0.8757],
        [0.3982, 0.9101, 0.6161, 0.9920],
        [0.7417, 0.5797, 0.4198, 0.9813]])

In [32]:
# Find out details about some tensor
print(f'{some_tensor}\n')
print(f'Shape of tensor: {some_tensor.shape}\n')
print(f'Datatype of tensor: {some_tensor.dtype}\n')
print(f'Device tensor is on: {some_tensor.device}\n')

tensor([[0.2222, 0.0057, 0.3002, 0.8757],
        [0.3982, 0.9101, 0.6161, 0.9920],
        [0.7417, 0.5797, 0.4198, 0.9813]])

Shape of tensor: torch.Size([3, 4])

Datatype of tensor: torch.float32

Device tensor is on: cpu



In [33]:
some_tensor_test = torch.rand(size=(4, 5), dtype=torch.float16, device='meta')
some_tensor_test

tensor(..., device='meta', size=(4, 5), dtype=torch.float16)

In [34]:
print(f'{some_tensor_test}\n')
print(f'Shape of tensor: {some_tensor_test.shape}\n')
print(f'Datatype of tensor: {some_tensor_test.dtype}\n')
print(f'Device tensor is on: {some_tensor_test.device}\n')

tensor(..., device='meta', size=(4, 5), dtype=torch.float16)

Shape of tensor: torch.Size([4, 5])

Datatype of tensor: torch.float16

Device tensor is on: meta



### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [35]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [36]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [37]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [39]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> (2,2)
* `(3, 2) @ (2, 3)` -> (3,3)



In [40]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[3.2622, 2.9691, 1.4533],
        [3.8691, 3.9809, 2.1634],
        [3.1313, 3.2905, 1.8642]])

In [41]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [44]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.27 ms, sys: 38 µs, total: 1.3 ms
Wall time: 3.4 ms


In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 44 µs, sys: 0 ns, total: 44 µs
Wall time: 47.9 µs


tensor(14)

### One of the most common erros in deep learning: shape errors

In [46]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) torch.mm is the same as torch.matmul (its an alias for writing less code)
#torch.matmul(tensor_A, tensor_B) RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [47]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [48]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [49]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [50]:
# The matrix multiplication operation works when tensor B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Output:\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max mean, sum, etc (tensor aggregation)

In [51]:
# Create a tensor
x=torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [52]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [53]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [54]:
torch.mean(x.type(torch.float32)), (x.type(torch.float32)).mean()

(tensor(45.), tensor(45.))

In [55]:
#Find de sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [56]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [58]:
x[0]

tensor(0)

In [59]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [60]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [61]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
#change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [64]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [65]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [66]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [67]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [68]:
x_reshaped.squeeze().shape

torch.Size([9])

In [69]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previous shape:  {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:  torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [70]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [71]:
x_permuted[0, 0, 0]

tensor(0.3190)

In [72]:
x_original[0, 0, 0]

tensor(0.3190)

In [73]:
x_original [0, 0, 0] = 728218
x_original [0, 0, 0], x_permuted [0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy.

In [74]:
# Create a tensor

import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [75]:
# Lets's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [76]:
# Let's index on the middle bracket (dim = 1)
x[0][2]

tensor([7, 8, 9])

In [77]:
x[0][1][1]

tensor(5)

In [78]:
# You can also use ":" to select "all" of a target dimension
x[:, 2, :]

tensor([[7, 8, 9]])

In [79]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2st dimension
x[0, 1, 1]

tensor(5)

In [80]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimensio

x[0][0][:]

tensor([1, 2, 3])

In [81]:
x[0][:][2]

tensor([7, 8, 9])

# Pytorch tensors $ Numpy

Numpy is a popular scientific Python numerical computing library.
Pytorch has functionality to interact with it.

* Data in Numpy, want in Pytorch tensor -> torch.from_numpy(ndarray)
* Pytorch tensor -> Numpy -> torch.Tensor.numpy()


In [82]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [84]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [85]:
#Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [86]:
numpy_tensor.dtype, tensor.dtype

(dtype('float32'), torch.float32)

In [87]:
# Change the tensor, whats happens to numpy_tensor ?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural networks learns:

start with random numbers -> tensor operations -> update random numbers to try
and make them better representations of the data -> again -> again ->...

To reduce the randomess in neural networks and Pytorch comes the concepts of a random seed.
Essentially what the random seed does is "flavour" the randomness

In [88]:
torch.rand(3, 3)

tensor([[0.4960, 0.3457, 0.5893],
        [0.1286, 0.1602, 0.6803],
        [0.4813, 0.3065, 0.4474]])

In [89]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8198, 0.5585, 0.5479, 0.6965],
        [0.1508, 0.6707, 0.3550, 0.8170],
        [0.2759, 0.5399, 0.0491, 0.2720]])
tensor([[0.8918, 0.2544, 0.9800, 0.5120],
        [0.6736, 0.8777, 0.4904, 0.7393],
        [0.6085, 0.3586, 0.4252, 0.8108]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


  ## Running tensors and Pytorch objects on the GPUs (and making faster computations)



### Getting a GPU

1 - Easiest - Use Google Colab for a free GPU (options to upgrade as well)

2 - Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU

3 - Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/

In [91]:
!nvidia-smi

Sun Jan 12 22:19:59 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with Pytorch

In [92]:
# Check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [93]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [95]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [98]:
# Create a tensor (defaut on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [99]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 4. Moving tensors back to CPU


In [100]:
# If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [101]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [102]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')