<a href="https://colab.research.google.com/github/viktoruebelhart/studies/blob/main/00_Pytorch_Bourke.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
## 00. Pytorch Fundamentals

In [21]:
!nvidia-smi

Sun Jan  5 14:33:08 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [22]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensor

### Creating tensor

Pytorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html



In [23]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [24]:
scalar.ndim

0

In [25]:
#Get tensor back as Python int
scalar.item()

7

In [26]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [27]:
vector.ndim

1

In [28]:
vector.shape

torch.Size([2])

In [29]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [30]:
MATRIX.ndim

2

In [31]:
MATRIX[1]

tensor([ 9, 10])

In [32]:
MATRIX.shape

torch.Size([2, 2])

In [47]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [48]:
TENSOR.ndim

3

In [49]:
TENSOR.shape

torch.Size([1, 3, 3])