<a href="https://colab.research.google.com/github/viktoruebelhart/studies/blob/main/00_Pytorch_Bourke.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
## 00. Pytorch Fundamentals

In [68]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [69]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensor

### Creating tensor

Pytorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html



In [70]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [71]:
scalar.ndim

0

In [72]:
#Get tensor back as Python int
scalar.item()

7

In [73]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [74]:
vector.ndim

1

In [75]:
vector.shape

torch.Size([2])

In [76]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [77]:
MATRIX.ndim

2

In [78]:
MATRIX[1]

tensor([ 9, 10])

In [79]:
MATRIX.shape

torch.Size([2, 2])

In [80]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [81]:
TENSOR.ndim

3

In [82]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/main/generated/torch.rand.html

In [83]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5046, 0.5561, 0.0183, 0.7881],
        [0.5123, 0.8314, 0.6041, 0.9439],
        [0.8860, 0.4983, 0.4090, 0.1062]])

In [84]:
#Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(3, 224, 224)  # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [85]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [86]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [87]:
ones.dtype

torch.float32

In [88]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [89]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & Deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensor not on the right device

In [91]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= torch.float32, # what datatype is the tensor (e.g. float32 or float16)
                               device= None, # what device is your tensor on
                               requires_grad= False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [92]:
float_32_tensor.dtype

torch.float32

In [93]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [94]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [95]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [96]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors

1. Tensors not right datatype   - `tensor.dtype`
2. Tensors not right shape      - `tensor.shape`
3. Tensor not on the right device - `tensor.device`

In [97]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0471, 0.0545, 0.9537, 0.8714],
        [0.1690, 0.6657, 0.7958, 0.0573],
        [0.4532, 0.1380, 0.7231, 0.6353]])

In [98]:
# Find out details about some tensor
print(f'{some_tensor}\n')
print(f'Shape of tensor: {some_tensor.shape}\n')
print(f'Datatype of tensor: {some_tensor.dtype}\n')
print(f'Device tensor is on: {some_tensor.device}\n')

tensor([[0.0471, 0.0545, 0.9537, 0.8714],
        [0.1690, 0.6657, 0.7958, 0.0573],
        [0.4532, 0.1380, 0.7231, 0.6353]])

Shape of tensor: torch.Size([3, 4])

Datatype of tensor: torch.float32

Device tensor is on: cpu



In [99]:
some_tensor_test = torch.rand(size=(4, 5), dtype=torch.float16, device='meta')
some_tensor_test

tensor(..., device='meta', size=(4, 5), dtype=torch.float16)

In [100]:
print(f'{some_tensor_test}\n')
print(f'Shape of tensor: {some_tensor_test.shape}\n')
print(f'Datatype of tensor: {some_tensor_test.dtype}\n')
print(f'Device tensor is on: {some_tensor_test.device}\n')

tensor(..., device='meta', size=(4, 5), dtype=torch.float16)

Shape of tensor: torch.Size([4, 5])

Datatype of tensor: torch.float16

Device tensor is on: meta



### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [101]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [102]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [103]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [104]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [105]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> (2,2)
* `(3, 2) @ (2, 3)` -> (3,3)



In [106]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[3.1876, 2.4413, 2.7179],
        [2.5459, 1.7961, 1.5166],
        [2.2628, 1.5768, 1.9209]])

In [107]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [108]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [109]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [110]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.62 ms, sys: 81 µs, total: 1.7 ms
Wall time: 2.13 ms


In [111]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 87 µs, sys: 8 µs, total: 95 µs
Wall time: 100 µs


tensor(14)

### One of the most common erros in deep learning: shape errors

In [112]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) torch.mm is the same as torch.matmul (its an alias for writing less code)
#torch.matmul(tensor_A, tensor_B) RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [113]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [114]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [115]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [116]:
# The matrix multiplication operation works when tensor B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Output:\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max mean, sum, etc (tensor aggregation)

In [117]:
# Create a tensor
x=torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [118]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [119]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [120]:
torch.mean(x.type(torch.float32)), (x.type(torch.float32)).mean()

(tensor(45.), tensor(45.))

In [121]:
#Find de sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [122]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [123]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [124]:
x[0]

tensor(0)

In [125]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [126]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)